### ISSUE TITLE
curl request for Game API 'create' not working

### ISSUE THREAD

**Issue by nriser** [ga-wdi-boston/project-issue-tracker-guide#32]
I'm trying to make my curl request for the create game request, but I keep getting a 404 Not Found response. I've tried two ways, one with POST (as it's written in the game api project repo), and another with GET. The token and ID were retrieved after I signed in.  I apologize in advance if I'm missing any other info! I'd appreciate any feedback. 

curl request in project-tictactoe/scripts/game-create.sh: 
```
#!/bin/bash
curl --include --request POST http://localhost:4741/games/$ID \
  --header "Authorization: Token token=$TOKEN" \
  --data ''

  echo
```
error message on grunt server: 
```
Started POST "/games/15" for ::1 at 2017-04-11 19:47:04 -0400

ActionController::RoutingError (No route matches [POST] "/games/15"):
  actionpack (4.2.7.1) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.7.1) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.7.1) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.7.1) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.7.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/static.rb:120:in `call'
  rack-cors (0.4.0) lib/rack/cors.rb:80:in `call'
  railties (4.2.7.1) lib/rails/engine.rb:518:in `call'
  railties (4.2.7.1) lib/rails/application.rb:165:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  puma (3.6.0) lib/puma/configuration.rb:225:in `call'
  puma (3.6.0) lib/puma/server.rb:578:in `handle_request'
  puma (3.6.0) lib/puma/server.rb:415:in `process_client'
  puma (3.6.0) lib/puma/server.rb:275:in `block in run'
  puma (3.6.0) lib/puma/thread_pool.rb:116:in `block in spawn_thread'
```

command I run in terminal, along with the error message below:
```
$ ID=15 TOKEN=BAhJIiU5NzE5ZTU0ZWZlNjg2NjZlN2JiOWRjYjhlNzM4ODZhNQY6BkVG--41dee1189ccf82dc42516eea6623366857e470f6 sh scripts/game-create.sh
HTTP/1.1 404 Not Found
Content-Type: text/html; charset=utf-8
X-Request-Id: bc2a179a-da95-4537-a84b-761eca67d271
X-Runtime: 0.021777
Vary: Origin
Content-Length: 1564

<!DOCTYPE html>
<html>
<head>
  <title>The page you were looking for doesn't exist (404)</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <style>
  body {
    background-color: #EFEFEF;
    color: #2E2F30;
    text-align: center;
    font-family: arial, sans-serif;
    margin: 0;
  }

  div.dialog {
    width: 95%;
    max-width: 33em;
    margin: 4em auto 0;
  }

  div.dialog > div {
    border: 1px solid #CCC;
    border-right-color: #999;
    border-left-color: #999;
    border-bottom-color: #BBB;
    border-top: #B00100 solid 4px;
    border-top-left-radius: 9px;
    border-top-right-radius: 9px;
    background-color: white;
    padding: 7px 12% 0;
    box-shadow: 0 3px 8px rgba(50, 50, 50, 0.17);
  }

  h1 {
    font-size: 100%;
    color: #730E15;
    line-height: 1.5em;
  }

  div.dialog > p {
    margin: 0 0 1em;
    padding: 1em;
    background-color: #F7F7F7;
    border: 1px solid #CCC;
    border-right-color: #999;
    border-left-color: #999;
    border-bottom-color: #999;
    border-bottom-left-radius: 4px;
    border-bottom-right-radius: 4px;
    border-top-color: #DADADA;
    color: #666;
    box-shadow: 0 3px 8px rgba(50, 50, 50, 0.17);
  }
  </style>
</head>

<body>
  <!-- This file lives in public/404.html -->
  <div class="dialog">
    <div>
      <h1>The page you were looking for doesn't exist.</h1>
      <p>You may have mistyped the address or the page may have moved.</p>
    </div>
    <p>If you are the application owner check the logs for more information.</p>
  </div>
</body>
</html>

```

I've also tried it with a GET request instead of a POST:

curl request in project-tictactoe/scripts/game-create.sh: 
```
#!/bin/bash
curl --include --request GET http://localhost:4741/games/$ID \
  --header "Authorization: Token token=$TOKEN" \
  --data ''

  echo
```
error message on grunt server: 
```
Started GET "/games/15" for ::1 at 2017-04-11 19:31:41 -0400
Processing by GamesController#show as */*
  Parameters: {"id"=>"15"}
  User Load (12.6ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT 1  [["token", "9719e54efe68666e7bb9dcb8e73886a5"]]
  Game Load (12.4ms)  SELECT  "games".* FROM "games" WHERE (player_x_id = 15 or player_o_id = 15) AND "games"."id" = $1 LIMIT 1  [["id", 15]]
[active_model_serializers] Rendered ActiveModel::Serializer::Null with Hash (0.24ms)
Completed 404 Not Found in 93ms (Views: 20.5ms | ActiveRecord: 55.3ms)
```

command I run in terminal, along with the error message below:
```
$ ID=14 TOKEN=BAhJIiVmODdmMDdjOWM5YWE2MTM0NzRkODNlNmUwMDkyN2U3MwY6BkVG--c5e0c87a931917a82984b92cffa9e1da51ce0570 sh scripts/game-create.sh
HTTP/1.1 404 Not Found
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Cache-Control: no-cache
Content-Type: application/json; charset=utf-8
X-Request-Id: f0262387-17ce-469c-825e-b59621a04ed1
X-Runtime: 0.044360
Vary: Origin
Transfer-Encoding: chunked

{"error":{"message":"Not Found"}}~/wdi/projects/project-tictactoe (game-api-create)
$ ID=15 TOKEN=BAhJIiU5NzE5ZTU0ZWZlNjg2NjZlN2JiOWRjYjhlNzM4ODZhNQY6BkVG--41dee1189ccf82dc42516eea6623366857e470f6 sh scripts/game-create.sh
HTTP/1.1 404 Not Found
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Cache-Control: no-cache
Content-Type: application/json; charset=utf-8
X-Request-Id: 50ec95d8-e540-471c-ad1a-7312bd986c2d
X-Runtime: 0.107895
Vary: Origin
Transfer-Encoding: chunked

{"error":{"message":"Not Found"}}~/wdi/projects/project-tictactoe (game-api-create)
```

**Comment by nriser** [comment]
I realized that this isn't the right place to send issue requests.
